- dart-runtime/lib/http_client.dart
- dart-runtime/pubspec.yaml
Fixes #11.
Note: package `get_version` was replaced by `package_info` because it was just a wrapper (see https://github.com/fluttercommunity/get_version/blob/master/lib/get_version.dart)
> dart-runtime: ignore package info error (information might not be available)

- node-runtime/src/http-client.ts
Node 8 doesn't have the `URL` global class. Instead, we need to import it from the "URL" package.
> Fix URL import for Node 8 support

- browser-runtime/src/encode-decode.ts
- node-runtime/spec/types/types.spec.ts
- node-runtime/src/encode-decode.ts
[In the previous sdkgen version, it was possible to return a string as a date/datetime and the encoder would accept it.](https://github.com/cubos/sdkgen/blob/122926fbfe2b116d51732f8a53d202b187d93739/src/codegen_types/datetime.cr#L8)
It was not possible to do that in this version, and this PR fixes that.
> Fix: Restore old date/datetime behavior

- cli/src/build.ts
- parser/spec/parser.spec.ts
- parser/src/ast.ts
- parser/src/parser.ts
> Deprecate 'get' and 'function' keywords by printing a warning on every usage

- browser-runtime/tsconfig.json
- cli/tsconfig.json
- dart-generator/tsconfig.json
- node-runtime/tsconfig.json
- parser/tsconfig.json
- typescript-generator/tsconfig.json
Node 8+ support ES2017, so we can enable it.
For browser-runtime this actually downgrades it to ES5 for better compatibility. (We don't need ES6 there)
> Upgrade node packages to ES2017 and downgrade browser package to ES5

- dart-generator/src/dart-client.ts
- dart-generator/src/helpers.ts
- typescript-generator/src/helpers.ts
This is safe because package versions are locked to be always the same, so there won't be multiple instances of the classes from different packages.
This also fixes a wrong usage of AnyPrimitiveType in the dart generator. It was renamed to JsonPrimitiveType a while ago.
> Use direct references to all types, avoiding using non-existing classes

- .github/workflows/test.yml
- browser-runtime/src/encode-decode.ts
- dart-generator/src/helpers.ts
- dart-runtime/lib/types.dart
- node-runtime/src/encode-decode.ts
- node-runtime/src/http-server.ts
- parser/src/ast.ts
- parser/src/compatibility/index.ts
- parser/src/lexer.ts
- parser/src/semantic/10_validate_annotations.ts
- parser/src/utils.ts
- typescript-generator/src/helpers.ts
- vscode-ext/syntaxes/sdkgen.tmLanguage.json
BigInt type was added to all targets. With that:
1. Node 8 was dropped. It doesn't support BigInts. And also, it doesn't have official support anymore.
2. Some code about removed types still existed. Those where removed.
BigInt values are encoded as string on the json buffer. But the decoder accepts receiving an integer. So it is safe to change any `int`, `uint` or `money` types into `bigint` without breaking changes for clients.
> Feat: bigint type

- dart-generator/src/dart-client.ts
Functions with void callback there are no typed return. The proposal of returning Future<void> allow us to make use of the object Future's methods, such as `.then()`.
> improvement: make void functions return Future<void>

- node-runtime/src/http-client.ts
http response event 'aborted' was not being captured, leading to promise not being fulfilled.
> fix: handle 'aborted' http response event

- csharp-generator/src/helpers.ts
```c#
class A {
}
A? x;
x.Value // Invalid
```
> fix: C#: When taking the optional of a class, ".Value" should not be generated

- parser/spec/parser.spec.ts
- parser/src/json.ts
`@description` on fields wasn't salved on `ast.json` previously. This PR fixes that.
> fix: Don't discard descriptions on fields

- csharp-generator/src/csharp-server.ts
- csharp-generator/src/helpers.ts
> Optimize C# code for language patterns

- node-runtime/src/http-client.ts
Code was destructuring a Map, causing it to return an empty object and thus not sending mapped values to server. Added the shortest one-liner to turn a map into an object in ES6 I could find.
> node client extra property was not being sent to server

- dart-runtime/lib/types.dart
> Fix added void type on decode and encode

- browser-runtime/src/http-client.ts
It was using 'name' from DOM instead
> Fix function name property in browser-runtime HTTP client

- dart-generator/src/helpers.ts
Handles `OptionalType` in `dart-runtime`'s `cast` with proper null-handling
Fixes #78
> Fix optional arrays in Dart

- node-runtime/spec/types.spec.ts
- typescript-generator/spec/helpers.spec.ts
- typescript-generator/src/helpers.ts
The current correct type usage for javascript BigInt in Typescript is `bigint`.
Reference: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html#bigint
> Use bigint type name for typescript instead of BigInt

- dart-generator/src/dart-client.ts
The way to declare a Dart class instance changed when the class constructors with @required tags were applied.
The old way:
```
(Map fields) => MyClass()
..id = fields["id"] as String
..name = fields["name"] as String,
```
The new way:
```
(Map fields) => MyClass(
id: fields["id"] as String,
name: fields["name"] as String
),
```
This pull request applies this fix, solving the warnings from the `client.dart` file.
ATTENTION: Further tests are required!
> [Dart] fix: Add named parameters to the classes constructors on StructTypeDescription

- playground/src/components/requestCard/errors/errors.scss
- playground/src/components/requestCard/errors/index.tsx
this fix stops the error message to overflow the card container, the error affect specially mobile users because they lack a larger screen.
> fix error display message container

- node-runtime/src/error.ts
- node-runtime/src/http-server.ts
When throwing an error in a function defined with `@throws` annotation, [sdkgen checks if the error type matches any of the error types specified in `@throws`, and if it doesn't, the type is replaced with Fatal](https://github.com/sdkgen/sdkgen/blob/a7348d82d35ccfdbe349453aa6a829de4f961c23/node-runtime/src/http-server.ts#L718-L733).
The problem is, if you throw an SdkgenError, [whose `type` doesn't have an setter](https://github.com/sdkgen/sdkgen/blob/a7348d82d35ccfdbe349453aa6a829de4f961c23/node-runtime/src/error.ts#L2-L4), it'll end in an unhandled rejection:
```
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot set property type of Error which has only a getter
at SdkgenHttpServer.executeRequest (/app/node_modules/@sdkgen/node-runtime/dist/src/http-server.js:574:42)
at …
```
> Fix error type overwrite

- .github/workflows/test.yml
- dart-runtime/lib/http_client.dart
Those are the stable releases that got at least 1 patch update in the last 12 months
> Upgrade Flutter on CI to 1.12.x, 1.17.x, 1.20.x, 1.22.x

- dart-generator/src/dart-client.ts
- kotlin-generator/src/android-client.ts
- parser/spec/parser.spec.ts
- parser/src/ast.ts
- parser/src/json.ts
- parser/src/parser.ts
- parser/src/semantic/10_validate_annotations.ts
- playground/src/stores/requests.ts
- typescript-generator/src/browser-client.ts
- typescript-generator/src/node-client.ts
- vscode-ext/syntaxes/sdkgen.tmLanguage.json
Example:
```
@hidden
fn getUsers(): User[]
```
Functions marked as `@hidden` won't show in the generated client targets or the playground. This is useful when deprecating an old function (without causing a breaking change) or when creating a function meant to be used as `@rest` only. Hidden functions can still be called from old clients or by someone manually. Do not use this for security!
> feat: implement "hidden" annotation

- node-runtime/spec/rest/rest.spec.ts
- node-runtime/spec/simple/api.sdkgen
- node-runtime/spec/simple/simple.spec.ts
- node-runtime/src/http-server.ts
Fixes an issue where errors were passed as `Type: Error: message` instead of `Type: message` to the clients
> fix: error messages coming with an `Error:` prefix

- node-runtime/spec/simple/simple.spec.ts
- typescript-generator/src/node-server.ts
There is no reason what so ever to use `api.err.NotFound()` instead of `throw new NotFound()`. Let's deprecate it.
> Deprecate api.err in favor of throw

- .github/workflows/release.yml
- .github/workflows/test.yml
- vscode-ext/package.json
- vscode-ext/syntaxes/sdkgen.tmLanguage.json
Before:
After:
This was already handled by the parser correctly.
---
Also: Add CI for publishing the extension.
> Fix: vscode multiline `@description` and `@arg`

- kotlin-generator/src/helpers.ts
Fixing error - Node was not able to decode when Android client was sending a `bytes` parameter. It expects no `\n` in the content.
> Kotlin - encode base64 with NO_WRAP option

- dart-runtime/lib/http_client.dart
Added 2 arguments in SdkgenHttpClient:
```
- Map extra
- Map<String, String> headers
```
Allowing to send custom headers and extra arguments
> feat: implements custm headers and extra arguments

- dart-generator/src/helpers.ts
Error classes were coming out as:
```
class [object Object] extends SdkgenErrorWithData<T>
```
> Fix Dart generated error classes code

- node-runtime/src/test-wrapper.ts
Fix: `apiTestWrapper` was typed incorrectly and could not be used.
> fix: apiTestWrapper typing

- dart-runtime/lib/http_client.dart
sdkgen wasn't handling `SdkgenErrorWithData` properly and rethrowing them as Fatal errors
> fix(dart-runtime): don't re-throw SdkgenErrorWithData as Fatal errors

- browser-runtime/src/encode-decode.ts
- node-runtime/spec/types.spec.ts
- node-runtime/src/encode-decode.ts
`new Date("whatever")` produces a instance of `Date` containing an invalid date. This value can't be encoded. Calling `toISOString()` on it throws.
> fix: don't encode invalid dates

- dart-generator/package.json
- node-runtime/spec/rest/api.sdkgen
- node-runtime/spec/rest/rest.spec.ts
- node-runtime/src/http-server.ts
- parser/package.json
- typescript-generator/package.json
This PR introduces two fixes that may be seen as breaking changes:
- When matching a route argument, don't allow "/" anymore.
@rest GET /hello/{arg}/123
fn someFunction(arg: string): string
Previously this could match `/hello/a/b/c/123` with `arg = "a/b/c"`. Now it can't.
- When more than one route do match, prefer the one with more matching non-argument characters.
@rest GET /hello/{arg}
fn someFunction1(arg: string): string
@rest GET /hello/special-{arg}
fn someFunction2(arg: string): string
Now `/hello/aaa` will match the `someFunction1` and `/hello/special-aaa` will match `someFunction2`.
I believe these changes makes everything more intuitive. It was just broken before.
> fix: Improve selection of best REST route when there is more than one match

- browser-runtime/src/encode-decode.ts
- dart-generator/package.json
- docs/releases.md
- node-runtime/package.json
- node-runtime/spec/rest/api.sdkgen
- node-runtime/spec/rest/rest.spec.ts
- node-runtime/spec/types.spec.ts
- node-runtime/src/encode-decode.ts
- node-runtime/src/http-server.ts
- parser/package.json
- playground/package.json
- typescript-generator/package.json
**Correções:**
- Correção no recebimento de objetos retornados pela API no browser-runtime ([#181](https://github.com/sdkgen/sdkgen/pull/181)).
- Correção no tratamento de rotas REST para que caso mais de uma rota encaixe com uma requisição, aquela que contém a maior quantidade de caracteres que não fazem parte dos argumentos seja escolhida ([#179](https://github.com/sdkgen/sdkgen/pull/179)).
- Mudança no tratamento de rotas REST de forma que argumentos do tipo `string` dentra da path não possam mais conter o caracter `/` ([#179](https://github.com/sdkgen/sdkgen/pull/179)).
- Validação de datas no browser-runtime e node-runtime de forma que uma data inválida não seja aceita ([#180](https://github.com/sdkgen/sdkgen/pull/180)).
- Atualização de dependências.
> Release 1.5.4

- node-runtime/src/http-server.ts
Previously `addHttpHandler` accepted a regexp with a partial match. Since 1.5.3 the regex must match the whole path.
> fix: playground regex

- parser/spec/parser.spec.ts
- parser/src/restparser.ts
As per https://tools.ietf.org/html/rfc2616#section-4.2, header names can have much more than only letters, numbers and dashes. Underscore `_` must be supported, for example.
> fix: support all valid header names

- parser/package.json
- parser/src/parser.ts
- parser/src/restparser.ts
Now `@sdkgen/parser` can be used from the Browser without Node imports.
> feat: allow parser to be usable from browser

- dart-runtime/lib/deviceinfo_io.dart
Searching `SingletonFlutterWindow` on `views` list causes `sdkgen_runtime` to fail on `makeRequest` calls
> fix(dart-runtime): use flutter window view

- browser-runtime/src/http-client.ts
Isso estava fazendo crashar as requisições dentro do eval()
```
DOMException: XMLHttpRequest.setRequestHeader: XMLHttpRequest state must be OPENED.
makeRequest http-client.js:142
```
O motivo de ter funcionado assim até agora, eu não sei :joy:
> Fix: setRequestHeader should be called after open()

- parser/src/parser.ts
Estava causando problemas com o webpack:
```
./node_modules/@sdkgen/parser/dist/src/parser.js:17:39-65 - Error: Module not found: Error: Can't resolve 'fs' in './node_modules/@sdkgen/parser/dist/src'
```
> Lazily init readFileSync

- browser-runtime/src/http-client.ts
sdkgen shouldn't dump stuff to console during runtime, the devs should decide if errors should be logged or not
> Remove console.error

- android-runtime/runtime/src/main/java/io/sdkgen/runtime/SdkgenHttpClient.kt
The ideia is to allow SdkgenHttpClient use and external customized OkHttpClient. This way it will be possible to create, by example, a customized OKhttpClient with an Interceptor to implement a CircuitBreaker.
The changes for this PR is only add a set modifier and change the acess modifier from httpClient to var.
> Add function to set OkhttpClient on SdkgenHttpClient.kt

- dart-runtime/lib/deviceinfo_io.dart
- dart-runtime/pubspec.yaml
This PR resolves the issue #579. Please, test it before merging.
> [Dart runtime]: replace package `device_info` to `device_info_plus`

- playground/src/app/sdkgen.service.ts
- playground/src/app/tab-editor/tab-editor.component.ts
This will allow users to set extras and hooks on advanced editor, just like a traditional SdkgenHttpClient instance
> Allow access to SdkgenHttpClient members on advanced editor

- node-runtime/src/swagger.ts
Previously the AST node was being inserted into the swagger example. Now it shows the correct information.
> fix: show correct error schema on swagger

- fsharp-generator/src/fsharp-server.ts
F# suporta tasks de forma nativa na versão 6, porém para utilizar na versão 5 é necessário instalar o [TaskBuilder.fs](https://www.nuget.org/packages/TaskBuilder.fs/) como dependência;
> fix: support tasks on net5 in Fsharp Generator

- node-runtime/src/context.ts
- node-runtime/src/http-server.ts
`Context` has now a `response` that allows users to, in any request (REST or sdkgen), override the `statusCode` and set headers.
> Allow user to override response's statusCode and headers

- docs/typescript_nodeserver/intro.md
- node-runtime/src/http-server.ts
This PR exposes `handleRequest` on `SdkgenHttpServer` instance
> feat: publish handleRequest for usage with http servers and cloud functions

- parser/spec/parser.spec.ts
- parser/src/json.ts
- parser/src/semantic/02_give_struct_and_enum_names.ts
- parser/src/semantic/08_collect_struct_and_enum_types.ts
- parser/src/semantic/analyser.ts
- parser/src/semantic/transformer.ts
This PR fixes three issues:
1. Detect duplicate types with the same name early on and throw an error. This prevents it from leaking into the codegen phase and generating invalid code with duplicated classes/interfaces.
2. If the same type is referred by multiple places of the AST (if it was inlined by the spread operator for example), it should not be duplicated, only one of them should be included.
3. If two types declared twice are identical they should be merged together and their parent nodes should be updated to point to the same type. Previously the duplication would be simply ignored.
Please review each of the commits separately. Their commit message explains each fix.
> Fix: Better handing of repeated identical types

- node-runtime/src/test-wrapper.ts
Currently, the `ctx` argument of functions used during tests is modified. The argument should not be modified ever, and a new object should be created.
> fix: avoid modifying ctx argument in apiTestWrapper

- dotnet-runtime/runtime/Helpers.fs
fix build error: 
```
Error: /home/runner/work/sdkgen/sdkgen/dotnet-runtime/runtime/Helpers.fs(249,5): error FS0026: This rule will never be matched [/home/runner/work/sdkgen/sdkgen/dotnet-runtime/runtime/runtime.fsproj]
```
> fix: remove duplicate line

- cli/src/build.ts
- parser/src/parser.ts
This makes it possible to do `sdkgen src/schemas/*.sdkgen -o src/generated/api.ts -t typescript_nodeserver`, including all files from a folder. Any shell glob pattern will work.
> feat: support multiple files as cli arguments

- parser/spec/parser.spec.ts
- parser/src/json.ts
Path variables were being sorted by name.
Fixes #712.
> fix: The order of path arguments in a rest annotation should be kept unchanged.

- dart-runtime/lib/http_client.dart
This PR adds interceptors to `dart-runtime` project, inspired by the famous dio package. Basically calls an fn in three moments:
- Before sending a request (`onRequest`) 
- After receiving a response (`onResponse`) 
- After an error occurs (`onError`)
all the developer needs to do is assign one of these fns.
> Add Interceptors on Dart Runtime

- dart-generator/src/helpers.ts
Add override on equality and toString generator functions to prevent warning from lint
> Add override decorator on equality and toString fns

- dart-generator/src/dart-client.ts
- node-runtime/spec/simple/simple.spec.ts
- parser/src/helpers.ts
- parser/src/index.ts
- typescript-generator/src/browser-client.ts
- typescript-generator/src/helpers.ts
- typescript-generator/src/node-client.ts
- typescript-generator/src/node-server.ts
- exposes typescript-generator `hasType` helper function on `parser`
- uses exposed `hasType` to conditionally import `decimal` and `typed_data`
> Dart import external type lib conditionally

- dart-generator/src/helpers.ts
- parser/src/semantic/10_check_duplicate_members_on_enum.ts
- parser/src/semantic/analyser.ts
Dart doesn't allow duplicate value on enum type.
Also resolves #739
> Check duplicate value on enum type

- browser-runtime/src/http-client.ts
`error.type` should keep the same type as it comes from the network. Reading `.name` of a class is not valid if the source is minified.
> fix: Function.name is not valid on minified js

- android-runtime/runtime/src/main/java/io/sdkgen/runtime/SdkgenHttpClient.kt
- kotlin-generator/src/android-client.ts
While creating a mock offline test version of an Android Application i noticed there wasn't a way to add interceptors to the httpClient.
- Added possible `Interceptor` to httpClient builder
- Added possible `networkInterceptor` to httpClient builder
This is 100% not needed to the normal utilization of sdkgen but only a possible option for mocked test scenarios
> Adding possibility of okhttp interceptors to android

- dart-generator/src/dart-client.ts
As `hashList` function is not used anymore #741 therefore `dart:ui` import is not need
> Fix: remove unnecessary dart import

- node-runtime/src/swagger.ts
Currently, the generated Swagger follows this structure:
```json
{
"openapi": "3.0.0",
"info": {
"title": "",
"version": ""
},
"paths": {
"route1": {},
"route2": {}
},
"definitions": {
"schemas": {
"definition1": {},
"definition2": {}
}
}
}
```
And this structure has 2 errors: one structural and one semantic.
```
Structural error at
should NOT have additional properties
additionalProperty: definitions
Jump to line 0
```
```
Semantic error at paths./register/company-user/availability.post.requestBody.content.application/json.schema.$ref
requestBody schema $refs must point to a position where a Schema Object can be legally placed
```
Corrections made:
- Renamed the definitions property to components. The 3.0 structure expects components.
- Semantic error fixed: Schemas must be inside …
> feat: add security definitions and fix swagger object structure

- node-runtime/src/swagger.ts
Changes:
- The Swagger `authorize` button is not hidden anymore
- Endpoints are separated by tags created by the first name of the path.
> feat: show swagger authorize button and better use of tags

- playground/src/app/simple-call/simple-call.component.html
- playground/src/app/simple-call/simple-call.component.ts
- playground/src/app/tab-nav/tab-nav.component.ts
This PR adds a new tab in the simple call page to add the extras to the request page to send extras along with the request without the need to use advanced editor
> feat(playground): add extras tab to simple-call-component

- packages/node-runtime/src/http-server.ts
Foi criado uma função publica para encapsular o comportamento do console.error, e assim permitir as API's sobrescreverem o comportamento dessa função se for necessário.
> Create logError function to encapsulate original console.error

- packages/dart-runtime/lib/http_client.dart
- packages/dart-runtime/lib/interceptors.dart
- packages/dart-runtime/test/interceptors_test.dart
This PR introduces an improvement to the use of sdkgen interceptors. The new approach allows multiple interceptors to be used in a chained fashion, improving flexibility and code organization. Additionally, an extension for interceptor lists has been added, making it easier to execute all interceptors registered for onRequest, onResponse, and onError events.
Motivation for Changes:
Previously, the SDK only allowed a single interceptor per event (`onRequest`, `onResponse`, `onError`). This limitation made it difficult to implement distinct functionalities, such as authentication, logging, and validation, at the same time.
Organization and Reuse:
Separating responsibilities into different classes (such as LogInterceptors and AuthInterceptors) improves code readability and maintainability. …
> feat: implement interceptor pattern for SdkgenHttpClient
