node-runtime/src/test-wrapper.ts

fix: files on ctx

---

node-runtime/src/http-client.ts

fix prettier on node-runtime

---

.github/workflows/release.yml
.github/workflows/release_dev.yml

See https://github.com/sdkgen/sdkgen/runs/522801760

fix: during release install a local version of the dependency, not a remote version that has been published seconds ago (might be unavailable)

---

parser/spec/parser.spec.ts
parser/src/semantic/10_validate_annotations.ts

fix: accept enums on rest calls

---

kotlin-generator/src/android-client.ts
kotlin-generator/src/helpers.ts

resolves #58 
resolves #57 
Add Parcelize to data classes, and add null default value for data class optional constructor parameters

Kotlin enhancements

---

kotlin-generator/src/android-client.ts

invoke callback on ui thread and create response handling funcion to reduce output size

Android client invoke callback on ui thread

---

node-runtime/src/test-wrapper.ts

fix: forward headers and extra on apiTestWrapper

---

kotlin-generator/src/android-client.ts
kotlin-generator/src/helpers.ts

fix deserialization with mangled properties

fix: android deserialization

---

playground/src/components/header/index.tsx
playground/src/components/requestCard/annotations/annotations.scss
playground/src/components/requestCard/bottom/index.tsx
playground/src/components/requestCard/header/index.tsx
playground/src/components/searchInput/index.tsx
playground/src/configuration/analytics.ts
playground/src/configuration/endpoint.ts
playground/src/configuration/index.ts
playground/src/configuration/sentry.ts
playground/src/containers/app/index.tsx
playground/src/containers/mainWrapper/index.tsx
playground/src/containers/mainWrapper/mainWrapper.scss
playground/src/containers/routes/index.tsx
playground/src/helpers/componentSwitch/index.tsx
playground/src/index.tsx
playground/src/resources/styles/main.scss
playground/webpack.config.js

this pull request remove not used env variables, functions and comments.

clean up and improvements on codebase

---

playground/src/components/requestCard/content/index.tsx

this is a fix for issue #97, responses need to be json compliant to be properly parsed.

fix playground response

---

cli/src/build.ts
cli/src/compatibility.ts
cli/src/index.ts
docs/cli.md

- Improve `--help` contents
- Add `--old` and `--new` options to `sdkgen compatibility`, while keeping the previous behavior untouched (not a breaking change)

feat(cli): improve cli options

---

node-runtime/src/swagger.ts

Added in the node-runtime the EmailPrimitiveType when generating the swagger

fix(swagger): Added in swagger parser Email Primitive Type

---

tsconfig.json

this make vscode work from the root

chore: add tsconfig to root dir

---

dart-generator/src/helpers.ts

Fixed MoneyPrimitiveType cast to int in dart generator

fix: fixed Money type cast to int

---

browser-runtime/src/encode-decode.ts
typescript-generator/spec/helpers.spec.ts
typescript-generator/src/browser-client.ts
typescript-generator/src/helpers.ts
typescript-generator/src/interfaces.ts
typescript-generator/src/node-client.ts
typescript-generator/src/node-server.ts

feat: use ArrayBuffer instead of Buffer on browser

---

dart-runtime/analysis_options.yaml
dart-runtime/lib/deviceinfo_io.dart
dart-runtime/lib/deviceinfo_web.dart
dart-runtime/lib/http_client.dart
dart-runtime/lib/types.dart
dart-runtime/pubspec.yaml
dart-runtime/test/types_test.dart

Following recommendations at https://pub.dev/packages/pedantic#using-the-lints.

chore: Use pedantic lint rules for dart-runtime

---

android-runtime/runtime/build.gradle

make android-runtime minSdkVersion 19 - Android 4.4 (KITKAT)

fix: change minSdkVersion from 21 to 19

---

node-runtime/spec/runtime/middleware.spec.ts
node-runtime/src/api-config.ts
node-runtime/src/http-server.ts
parser/spec/lexer.spec.ts
parser/spec/parser.spec.ts
parser/src/lexer.ts
parser/src/parser.ts
parser/src/token.ts
typescript-generator/src/node-server.ts

feat: remove deprecated features

---

README.md
docs/primeiro-projeto.md
node-runtime/package.json
node-runtime/spec/rest/rest.spec.ts
node-runtime/spec/runtime/errors.spec.ts
node-runtime/spec/runtime/middleware.spec.ts
node-runtime/spec/simple/simple.spec.ts
node-runtime/src/api-config.ts
node-runtime/src/context-storage.ts
node-runtime/src/execute.ts
node-runtime/src/http-client.ts
node-runtime/src/index.ts
typescript-generator/src/node-server.ts

Fixes #198.
This is a major change.

feat: implement useSdkgenContext()

---

browser-runtime/src/http-client.ts

Adding error hook on sdkgen http client, to catch sdkgen erros

feat: add error hook on SdkgenHttpClient catch

---

ios-runtime/_Pods.xcodeproj

Está fazendo o Git do VS Code crashar ao commitar
```
> git add -A -- .
error: open("ios-runtime/_Pods.xcodeproj"): Invalid argument
error: unable to index file 'ios-runtime/_Pods.xcodeproj'
fatal: updating files failed
```

Remove invalid symlink

---

dart-runtime/lib/deviceinfo_io.dart

Adds proper string for each device type.

feat: improve device type string for all platforms

---

.github/workflows/release.yml
.github/workflows/release_dev.yml
playground/src/app/app.module.ts
playground/src/app/console/console.component.scss
playground/src/app/dialog-about/dialog-about.component.html
playground/src/app/dialog-about/dialog-about.component.scss
playground/src/app/dialog-about/dialog-about.component.ts
playground/src/app/sdkgen.docs.ts
playground/src/app/sdkgen.service.ts
playground/src/app/tab-home/tab-home.component.scss
playground/src/app/tab-nav/tab-nav.component.html
playground/src/app/tab-nav/tab-nav.component.scss
playground/src/app/tab-nav/tab-nav.component.ts
playground/src/app/type-details/type-details.component.html
playground/src/styles.scss
playground/tsconfig.json

Prepare for Playground stable release

---

parser/spec/parser.spec.ts
parser/src/semantic/04_check_dont_return_secret.ts
parser/src/semantic/09_validate_annotations.ts

Fix @rest annotation !secret issue: #209  https://github.com/sdkgen/sdkgen/issues/209\

feat: add secret rest annotation validation

---

dart-runtime/lib/http_client.dart

Example: https://replit.com/@JosCleitonCleit/DartToString

Feat: Helpful message on Dart SdkgenError 

---

.github/workflows/release.yml
.github/workflows/release_dev.yml
.github/workflows/test.yml
dart-runtime/lib/deviceinfo_io.dart
dart-runtime/pubspec.yaml

chore: update flutter sdk

---

dart-generator/src/dart-client.ts

fix(dart-generator): store in a variable before casting the result

---

packages/node-runtime/src/context.ts
packages/node-runtime/src/http-server.ts
packages/node-runtime/src/test-wrapper.ts

Add raw query string to `ContextRequest` on node-runtime.

feat(node-runtime): add query to ctx

---

packages/browser-runtime/src/encode-decode.ts

Fix to maintain encoding and decoding compatibility from bytes type to Buffer in the browser runtime.

Fix: encode and decode bytes from Buffer
